// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SendSmsCallAlerts.Data;

#nullable disable

namespace SendSmsCallAlerts.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SendSmsCallAlerts.Models.AllScheduledJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ContactDetailId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CustomDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JobBookDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JobCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SchedulerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactDetailId");

                    b.HasIndex("SchedulerId");

                    b.ToTable("AllScheduledJobs");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.ContactDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactDetail");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.ForwardNum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ForwardNum");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.HangfireJobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HangfireJobLogs");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.IntroSms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IntroSms");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.IntroSmsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IntroSmsHistory");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.IvrOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Num")
                        .HasColumnType("int");

                    b.Property<string>("TwilioNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IvrOption");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.JobSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactDetailId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JobBookDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Scheduler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactDetailId");

                    b.ToTable("JobSchedule");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.MmsLinks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchedulerId")
                        .HasColumnType("int");

                    b.Property<int>("SmsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MmsLinkss");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.OptOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OptOuts");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.OptionInstructions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructionOrder")
                        .HasColumnType("int");

                    b.Property<int>("IvrId")
                        .HasColumnType("int");

                    b.Property<string>("TwilioNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OptionInstruction");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.RunFrom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RunFromName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RunFrom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RunFromName = "Today Date"
                        },
                        new
                        {
                            Id = 2,
                            RunFromName = "Custom Date"
                        },
                        new
                        {
                            Id = 3,
                            RunFromName = "Job Book Date"
                        },
                        new
                        {
                            Id = 4,
                            RunFromName = "Job Created Date"
                        });
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.Scheduler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JobBookDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RunFromId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("TimeToRunId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("executionDateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("executionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("fromNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("onceOrRepeat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("schedulerFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smsBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("templateOrAudioId")
                        .HasColumnType("int");

                    b.Property<string>("toNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RunFromId");

                    b.HasIndex("TimeToRunId");

                    b.ToTable("Schedulers");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.SmsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactDetailId")
                        .HasColumnType("int");

                    b.Property<string>("IsReadYesOrNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScheduledJobId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("dt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fromNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smsBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smsDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactDetailId");

                    b.ToTable("SmsDetails");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.SmsTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("imgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("templateBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SmsTemplates");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.TimeToRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HourCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TimeToRun");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HourCount = 0,
                            Name = "Now"
                        },
                        new
                        {
                            Id = 2,
                            HourCount = 24,
                            Name = "24 Hour"
                        },
                        new
                        {
                            Id = 3,
                            HourCount = 48,
                            Name = "48 Hour"
                        },
                        new
                        {
                            Id = 4,
                            HourCount = 72,
                            Name = "3 days"
                        },
                        new
                        {
                            Id = 5,
                            HourCount = 96,
                            Name = "4 days"
                        },
                        new
                        {
                            Id = 6,
                            HourCount = 120,
                            Name = "5 days"
                        },
                        new
                        {
                            Id = 7,
                            HourCount = 144,
                            Name = "6 days"
                        },
                        new
                        {
                            Id = 8,
                            HourCount = 168,
                            Name = "7 days"
                        },
                        new
                        {
                            Id = 9,
                            HourCount = 720,
                            Name = "1 Month"
                        },
                        new
                        {
                            Id = 10,
                            HourCount = 4320,
                            Name = "6 Months"
                        },
                        new
                        {
                            Id = 11,
                            HourCount = 8760,
                            Name = "1 Year"
                        },
                        new
                        {
                            Id = 12,
                            HourCount = -1,
                            Name = "Enter Custom Days and Hours"
                        });
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.AllScheduledJob", b =>
                {
                    b.HasOne("SendSmsCallAlerts.Models.ContactDetail", "ContactDetail")
                        .WithMany()
                        .HasForeignKey("ContactDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SendSmsCallAlerts.Models.Scheduler", "Scheduler")
                        .WithMany()
                        .HasForeignKey("SchedulerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactDetail");

                    b.Navigation("Scheduler");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.JobSchedule", b =>
                {
                    b.HasOne("SendSmsCallAlerts.Models.ContactDetail", "ContactDetail")
                        .WithMany("JobSchedules")
                        .HasForeignKey("ContactDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactDetail");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.Scheduler", b =>
                {
                    b.HasOne("SendSmsCallAlerts.Models.RunFrom", "RunFrom")
                        .WithMany()
                        .HasForeignKey("RunFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SendSmsCallAlerts.Models.TimeToRun", "TimeToRun")
                        .WithMany()
                        .HasForeignKey("TimeToRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunFrom");

                    b.Navigation("TimeToRun");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.SmsDetail", b =>
                {
                    b.HasOne("SendSmsCallAlerts.Models.ContactDetail", "ContactDetail")
                        .WithMany()
                        .HasForeignKey("ContactDetailId");

                    b.Navigation("ContactDetail");
                });

            modelBuilder.Entity("SendSmsCallAlerts.Models.ContactDetail", b =>
                {
                    b.Navigation("JobSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
